if(!require("shinyjs")) install.packages("shinyjs",dependencies = TRUE)
if(!require("shiny")) install.packages("shiny")
if(!require("shinydashboard")) install.packages("shinydashboard")
if(!require("DT")) install.packages("DT")
if(!require("ggplot2")) install.packages("ggplot2")
if(!require("dplyr")) install.packages("dplyr")
if(!require("treemapify")) install.packages("treemapify")
if(!require("purrr")) install.packages("purrr")
if(!require("rpart")) install.packages("rpart")
if(!require("ISLR")) install.packages("ISLR")
if(!require("rpart.plot")) install.packages("rpart.plot")
if(!require("party")) install.packages("party")
if(!require("CHAID")) install.packages("CHAID", repos = "http://R-Forge.R-project.org", type = "source")
if(!require("fastDummies")) install.packages("fastDummies")
if(!require("pROC")) install.packages("pROC")
if(! require("comprehenr")) install.packages("comprehenr")
if(! require("ROSE")) install.packages("ROSE")

library(comprehenr)
library(shiny)
library(shinydashboard)
library(shinyjs)
library(DT)
library(ggplot2)
library(dplyr)
library(treemapify)
library(purrr)
library(rpart)
library(party)
library(CHAID)
library(ISLR)
library(rpart.plot)
library(fastDummies)
library(pROC)
library(ROSE)
useShinyjs()


