library(comprehenr)
library(shiny)
library(shinydashboard)
library(DT)
library(ggplot2)
library(dplyr)
library(treemapify)
library(purrr)
library(rpart)
library(party)
library(ISLR)
library(rpart.plot)
library(fastDummies)
library(pROC)
library(ROSE)
library(xlsx)
library(readxl)
library(rsconnect)
library(partykit)
library(devtools)
#install_version("Formula", version = "1.2.5", repos = "http://cran.us.r-project.org") necessary for first deployment (shiny)




