if(!require("shiny")) install.packages("shiny",repos='http://cran.us.r-project.org')
if(!require("shinydashboard")) install.packages("shinydashboard",repos='http://cran.us.r-project.org')
if(!require("DT")) install.packages("DT",repos='http://cran.us.r-project.org')
if(!require("ggplot2")) install.packages("ggplot2",repos='http://cran.us.r-project.org')
if(!require("dplyr")) install.packages("dplyr",repos='http://cran.us.r-project.org')
if(!require("treemapify")) install.packages("treemapify",repos='http://cran.us.r-project.org')
if(!require("purrr")) install.packages("purrr",repos='http://cran.us.r-project.org')
if(!require("rpart")) install.packages("rpart",repos='http://cran.us.r-project.org')
if(!require("ISLR")) install.packages("ISLR",repos='http://cran.us.r-project.org')
if(!require("rpart.plot")) install.packages("rpart.plot",repos='http://cran.us.r-project.org')
if(!require("party")) install.packages("party",repos='http://cran.us.r-project.org')
if(!require("CHAID")) install.packages("CHAID", repos = "http://R-Forge.R-project.org", type = "source")
if(!require("fastDummies")) install.packages("fastDummies",repos='http://cran.us.r-project.org')
if(!require("pROC")) install.packages("pROC",repos='http://cran.us.r-project.org')
if(! require("comprehenr")) install.packages("comprehenr",repos='http://cran.us.r-project.org')
if(! require("ROSE")) install.packages("ROSE",repos='http://cran.us.r-project.org')
if(! require("xlsx")) install.packages("xlsx",repos='http://cran.us.r-project.org')
if(! require("readxl")) install.packages("readxl",repos='http://cran.us.r-project.org')
if(! require("rsconnect")) install.packages("rsconnect")

library(comprehenr)
library(shiny)
library(shinydashboard)
library(DT)
library(ggplot2)
library(dplyr)
library(treemapify)
library(purrr)
library(rpart)
library(party)
library(CHAID)
library(ISLR)
library(rpart.plot)
library(fastDummies)
library(pROC)
library(ROSE)
library(xlsx)
library(readxl)
library(rsconnect)





